aws:
  ec2_tags:
    start_stop_schedule : "true"
  region: us-east-2
  rds_tags:
    start_stop_schedule : "true"
  aws_profile: trademo

k8s: 
  context: "internal-trademo.com"
  namespaces: ["default","test"]
  replicas: 3
  deployment_annotations:
    start_stop_schedule : "true"
  sts_annotations:
    start_stop_schedule : "true"

actions_on:
    - k8s:
        - deployment
        - sts
    
    - aws:
        - ec2
        - rds