
aws:
  ec2_tags:
    start_stop_schedule : "true"
  region: us-east-1
  rds_tags:
    start_stop_schedule : "true"
  aws_profile: pankaj



k8s: 
  context: "minikube"
  namespace: "default"
  replicas: 3
  deployment_annotations:
    start_stop_schedule : "true"
  sts_annotations:
    start_stop_schedule : "true"

actions_on:
    - k8s:
        - deployment
        - sts
    
    - aws:
        - ec2